name: bump version

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  version_bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Standard Version
        # You may pin to the exact commit or the version.
        # uses: qzb/standard-version-action@a7d1f3c8e81f96976e1af5f6df576a55b4398d2b
        uses: qzb/standard-version-action@v1.0.5

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "[create-pull-request] automated change [skip azurepipelines]"
